# Generated by Django 5.1.1 on 2024-09-12 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skycom', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nota',
            name='nota1',
        ),
        migrations.RemoveField(
            model_name='nota',
            name='nota2',
        ),
        migrations.RemoveField(
            model_name='nota',
            name='nota3',
        ),
        migrations.AddField(
            model_name='nota',
            name='nota',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='nota',
            name='tipo_evaluacion',
            field=models.CharField(default='Examen', max_length=100),
        ),
    ]
